import sys
sys.path.insert(0, 'research/market-runs/nishinomiya-eikaiwa-juku-20260930/work')
from mk import *

M = "https://www.mapion.co.jp/phonebook/M11022/28204/"

# ---- batch 01 (visual verified) ----
b01 = [
 rec("lead-1316e07acb","uncertain","moderate","advance","個人塾らしく西宮で18年と記載。トップの視覚確認で導線・レイアウトの改善余地の可能性","トップに「西宮で18年」、塾長日記・講師募集のメニューあり。更新日付は未確認","https://www.misorajyuku.com/","desktopはグローバルナビが横に見切れ、mobileは本文が右端で切れて見える。装飾的なバナー中心で情報階層が長い(画像 lead-1316e07acb-top-desktop/mobile.png)","https://www.misorajyuku.com/","https://www.misorajyuku.com/",vis="verified"),
 rec("lead-6356a7a80d","uncertain","none","defer","個人経営・少人数で公式サイトは整っており、トップ上のWeb上の明確な差は見えない。次の確認: 問い合わせ・体験申込導線、更新頻度、実績掲載の有無","公式サイトあり、定員10名の少人数制・算数数学特化を記載。最新更新日は未確認","https://yamasakijuku.jp/","desktop/mobileとも大きなヒーロー画像と明快なコピーでレスポンシブ崩れ・古さは見えない","https://yamasakijuku.jp/","https://yamasakijuku.jp/",vis="verified"),
 rec("lead-53a69b8477","active","moderate","advance","西宮・宝塚の少人数塾で、お知らせに新コース・体験の告知あり。mobile表示に余白ずれがあり改善余地の可能性","お知らせに『小学生お預かり+学びクラス開講』『テスト対策無料体験』等の告知(日付表示なし)","https://www.tohmonjuku.net/","mobileで左側に約86pxの不自然な余白があり全体が右にずれ右端メニューが見切れる。desktopは中央幅の狭いレイアウトで文字・装飾が混在","https://www.tohmonjuku.net/","https://www.tohmonjuku.net/",vis="verified"),
 rec("lead-7b330dc6a6","uncertain","none","defer","サイトは整っており、トップ上のWeb上の明確な差は見えない。ブログ・アカウント機能も運用済み。次の確認: ブログ更新頻度、写真・スタッフ紹介など発信内容","電話番号・お問い合わせボタン・ブログ・マイアカウントを掲載。最新更新日は未確認","https://chigakudo.com/","desktop/mobileとも整ったレイアウト、mobile下部固定ナビ(MENU/ホーム/アクセス/お問い合わせ)あり","https://chigakudo.com/","https://chigakudo.com/",vis="verified"),
 rec("lead-1030fb437c","active","moderate","advance","2026-09-16付の新着記事があり活動中。トップがブログ形式で入口・導線の整理余地の可能性","新着記事に2026.09.16『中学生まなびサポートコースを開設』等。1985年創立の少人数制と記載","https://asukajuku.com/","トップがブログ記事一覧+サイドバー形式で塾の特徴・体験導線が最初に見えにくい。mobileはヘッダー文字が見切れる","https://asukajuku.com/","https://asukajuku.com/",vis="verified"),
 rec("class-e-73fec150a5","uncertain","none","advance","個人運営らしい子供〜大人の英会話教室で活動の手掛かりあり。導線は既にあるが独自の写真・発信が使えるため追加確認の価値あり","甲東園駅徒歩3分、体験レッスン申込ボタン、電話・住所、ブログ・生徒様の声・Instagram導線あり。最新更新日は未確認","https://class-e-jp.com/","desktop/mobileとも写真中心で体験申込ボタン・電話が上部にあり導線は明確","https://class-e-jp.com/","https://class-e-jp.com/",vis="verified"),
 rec("lead-c342637171","active","moderate","advance","2026-07-30付のお知らせあり活動中。西宮駅近くの小規模スクール。mobileヘッダー崩れなどWeb上の改善余地の可能性","お知らせに2026/07/30『夏季休暇のお知らせ』、2025/12/01『新規入会者募集中』。西宮で15周年と記載","https://www.marvinschool.com/","mobileでロゴ・電話番号・ナビが重なり右端で見切れる。desktopはグラデーションのナビなど古い印象","https://www.marvinschool.com/","https://www.marvinschool.com/",vis="verified"),
 rec("aie-981f9e2aff","active","unknown","stop","複数キャンパスと国際高校を運営する中規模以上の組織で個人・小規模の対象から外れる可能性が高い。今回は深掘りしない(恒久除外ではない)","西宮キャンパスの営業時間・住所・電話・メールを掲載。兵庫県英検合格者数1位、AIE国際高校を併記","https://aie-campus.com/campus/nishinomiya/","組織サイトの下層(校ページ)で整ったデザイン。本部運営のため店舗単位のWeb裁量は不明","https://aie-campus.com/campus/nishinomiya/","https://aie-campus.com/campus/nishinomiya/",vis="verified"),
 rec("lead-dfc5d2610d","active","none","stop","全国展開の英検専門塾の教室ページ(本部運営の資料請求誘導型)で個人・小規模の対象外","教室一覧・資料請求フォーム・英検合格者10,000人超の訴求を掲載する本部運営型ページ","https://eiken-academy.com/class-2/hyougo/koshienguchi/","本部管理の統一LPで整った作り","https://eiken-academy.com/class-2/hyougo/koshienguchi/","https://eiken-academy.com/class-2/hyougo/koshienguchi/","複数教室展開の英検アカデミーの教室(本部運営の統一サイト・全国訴求)で個人・小規模Segment対象外。出典 https://eiken-academy.com/class-2/hyougo/koshienguchi/","verified"),
 rec("lead-842a64e418","uncertain","moderate","advance","苦楽園口の個人運営らしい英語スクール。月間お便りが空欄、mobileでナビが見切れるなどWeb上の改善余地の可能性","申込ボタン、ブログ、クラス一覧、生徒とネイティブ講師の写真を掲載。更新日付は未確認","https://www.brightfutures.co.jp/","desktopは『月間お便り』枠が空白。mobileはボタン・ナビが右に見切れる。ナビ色が多色で階層がやや散漫","https://www.brightfutures.co.jp/","https://www.brightfutures.co.jp/",vis="verified"),
 rec("lead-c1b1f395d4","uncertain","moderate","advance","夙川駅近くの少人数英会話。電話・LINE・体験申込の導線はあるが、トップの情報階層やレイアウトに整理余地の可能性","電話・LINE・無料体験・料金を掲載。最新更新日は未確認","https://www.prevail-jp.com/","desktopは右側が大きく空白でリンク下線文字が並ぶ縦長構成。mobileはヘッダーロゴが見切れメニューボタンが重なる","https://www.prevail-jp.com/","https://www.prevail-jp.com/",vis="verified"),
 rec("lead-cab16f606d","active","unknown","defer","スミス英会話はFC系ブランドの可能性が高いが、校ページは講師個人の紹介で独自運営の余地も残る。次の確認: 運営主体(本部直営かオーナー運営か)と校独自の発信有無","甲東園校ページに2003年開校、講師の紹介、総合受付フリーダイヤルを掲載","https://smithweb.co.jp/kotoen/","本部共通テンプレートの校ページで校単独のWeb裁量は不明","https://smithweb.co.jp/kotoen/","https://smithweb.co.jp/kotoen/",vis="verified"),
 rec("lead-769a59dd9f","active","none","stop","トップで別地域(JR和歌山駅前)の新規開校を告知する複数教室運営の学習塾で個人・小規模対象から外れる可能性が高い。今回は深掘りしない(恒久除外ではない)","トップに『10/2新規開校 JR和歌山駅前教室』のバナー","https://manabikobetsu.info/","全画面バナー形式の本部運営サイト","https://manabikobetsu.info/","https://manabikobetsu.info/",vis="verified"),
 rec("lead-eb4783ec93","uncertain","unknown","advance","西宮北口の1校運営らしい個別指導塾で公式サイトが稼働。キャプチャがWebサーバ初期画面のため実際の表示・導線を要確認(再撮影)","検索結果に公式サイトの各ページと西宮北口校の説明、Xが表示。無料体験・入塾金無料を記載","https://kobetsu-fit.net/","取得キャプチャは『It works!』のみで実サイト内容と食い違うためvisualはunverified","https://kobetsu-fit.net/","https://kobetsu-fit.net/"),
 rec("lead-ef059e0b6f","active","unknown","stop","開進館は大手の複数校展開学習塾でSegment対象外","開進館の公式ドメイン内の西宮北口校ページ","https://www.kaishinkan.net/school/nishinomiya/nishikita/","大手チェーンのためweb_gapは評価しない","https://www.kaishinkan.net/school/nishinomiya/nishikita/","https://www.kaishinkan.net/school/nishinomiya/nishikita/","開進館は複数校展開の大手学習塾で個人・小規模Segment対象外。出典 https://www.kaishinkan.net/school/nishinomiya/nishikita/"),
 rec("j-s-english-club-17c9f2eadf","uncertain","unknown","defer","公式サイトはあるが視覚画像がなく確認できていない。段上西・段上幼稚園など複数教室の可能性。次の確認: トップの表示状態、教室数と運営規模、更新有無","検索でj-s.clubのクラス紹介ページが表示され段上西教室と段上幼稚園教室の存在が示される。更新日は未確認","http://j-s.club/classes.html","スクリーンショットは取得失敗でmetadataのみ","https://j-s.club","https://j-s.club"),
 rec("a-english-1bc5ac1916","uncertain","moderate","advance","個人運営らしい子供英語教室(講師20年)で無料ビルダーの簡易サイトかつ表示が未完成に見え、Web上の提案余地の可能性","トップに『週2回のネイティブ英語教室』『20年教師の私とネイティブ先生が待っています』、英検合格実績を掲載。更新日は未確認","https://aenglish.amebaownd.com","Ameba Owndの広告バナーが上部に出る無料プラン表示。ヒーロー下が黄色の空白領域で内容がなく、mobileでは本文が右端で見切れる","https://aenglish.amebaownd.com","https://aenglish.amebaownd.com",vis="verified"),
 rec("lead-e9151751f1","active","moderate","advance","1970年から続く教会併設の英会話(夙川クリスチャンセンター)で、10/6新学期の入会キャンペーンを告知し活動中。mobile表示の余白ずれなど改善余地の可能性","トップに『10/6(火)〜新学期スタート』『新学期入会特別キャンペーン』『10/5オープン受付&個別相談会』を掲載、2026年表記あり","https://christian-center.com","desktopはロゴが小さくヘッダーが余白の多い構成。mobileは左に約86pxの余白で全体が右にずれ体験予約ボタンが右端で見切れる","https://christian-center.com","https://christian-center.com",vis="verified"),
]
save("triage-01-out.jsonl", b01)

# ---- batch 02 ----
b02 = [
 rec("phillips-english-school-dcc6b3c85e","uncertain","moderate","advance","個人運営とみられる英会話教室。営業時間・連絡先は掲載あるが更新日不明。トップは階層が弱く整理余地の可能性。mobile未確認","トップに営業時間(火〜金10-20時/土9-19時)、電話・メール、教室写真ギャラリー掲載。更新日は不明","https://philipsenglishschool.com","desktopトップ: ヘッダーの文字色・サイズが混在し階層が弱い。ナビは小さい文字。予約導線は電話/メール表記のみ(フォーム未確認)","https://philipsenglishschool.com","https://philipsenglishschool.com",vis="verified"),
 rec("aire-a3a55ae5e9","uncertain","none","stop","サイトは整っており明確な提案余地がトップから見えない。今回は深掘りしない(恒久除外ではない)","阪神西宮駅徒歩3分、電話番号、4コース案内を掲載。更新日は未確認","https://aire-eikaiwa.com","desktopトップ: 4コースをカード化、階層・余白とも整理済み、電話導線あり","https://aire-eikaiwa.com","https://aire-eikaiwa.com",vis="verified"),
 rec("lead-55e5aacbfc","uncertain","unknown","advance","西宮の中高生向け塾の公式サイトあり。トップは写真中心で情報が抽象的、授業料・問い合わせ導線の実態は追加確認で判断が変わり得る","公立中高向け授業の案内、授業料・アクセス・問い合わせのナビあり。更新日は不明","https://terakoyajyuku.com/","desktopトップ: 大きな一枚写真と汎用的コピー、電話・予約導線が最上部に見えない。下層未確認のためgap判断保留","https://terakoyajyuku.com/","https://terakoyajyuku.com/",vis="verified"),
 rec("iteen-500e54c9c9","active","unknown","defer","iTeenブランドの校舎でFC/本部運営の可能性。独自運営可否・サイトの運営主体が未確認","入塾生募集中、電話・受付時間、無料体験WEB予約を掲載","https://nishinomiya-programming.com/","desktopトップ: 予約導線は充実。教室名は「produce by iTeen 西宮津門校」でFC形態の可能性","https://nishinomiya-programming.com/","https://nishinomiya-programming.com/",vis="verified"),
 rec("lead-8fa8566dfb","active","none","stop","6校舎展開のプログラミングスクールチェーンで英会話・学習塾の個人小規模Segment対象外","体験レッスン申込・電話・受付時間掲載","https://8x9.jp/school/nishinomiyakitaguchi/","トップ上部に六甲道本校/西宮北口校/名谷校/姫路校等のタブ。本部一元管理のサイト","https://8x9.jp/school/nishinomiyakitaguchi/","https://8x9.jp/school/nishinomiyakitaguchi/","複数校舎展開のプログラミングスクールチェーン(https://8x9.jp/school/nishinomiyakitaguchi/ の校舎タブで確認)。英会話/学習塾の個人・小規模Segment対象外","verified"),
 rec("lead-4c67e4056f","uncertain","moderate","advance","個人運営の高校受験塾。Wix無料プランのバナー表示、文字・背景色が過密で古い印象。問い合わせ導線もトップで見えず整理余地の可能性","「西宮で塾歴51年」「合格率100%」、電話0798-23-0082を看板画像で掲載。更新日は不明","https://shukugawa0082.wixsite.com/shukuei","desktopトップ: Wix広告バー表示、強い色のグラデ背景に赤青の大きな文字が混在し階層が不明瞭。予約・フォーム導線は最上部に見えない","https://shukugawa0082.wixsite.com/shukuei","https://shukugawa0082.wixsite.com/shukuei",vis="verified"),
 rec("lead-5eae50323e","active","none","stop","サイトは最近更新済み(Last Updated 2026/09/30)で整理も良好、明確な提案余地が見えない。今回は深掘りしない","NEWS「充実の秋、目指しましょう。生徒さん募集中です」、Last Updated 2026/09/30、1976年創立","http://www.hamada-juku.com/","desktopトップ: ヒーロー、CTA(問い合わせ・電話)、実績数値が整理されている","http://www.hamada-juku.com/","http://www.hamada-juku.com/",vis="verified"),
 rec("lead-c339ec6c0f","active","moderate","advance","少人数の地域塾で最近の募集・カレンダーあり。旧来型CMSレイアウトでTikTok/学童など情報が詰まり整理余地の可能性","「2学期入塾生募集中」、説明会日程、2026年9月の開講日カレンダー、TikTok埋込を掲載","https://kitaguchi-juku.com/","desktopトップ: 旧来型の3カラム構成、サイドバーに多数の要素、赤・橙・青の文字が混在し階層が散漫。電話導線は上部にあり","https://kitaguchi-juku.com/","https://kitaguchi-juku.com/",vis="verified"),
 rec("nuance-0e6f5738e6","uncertain","moderate","advance","子供英会話を複数駅で展開するが校長運営の独立教室の可能性。トップは同一画像の重複とヘッダー整理不足で、規模確認とあわせ追加確認の価値あり","無料体験レッスン実施中の画像、クラス・教室・保護者の声・校長の本等のナビ。更新日は不明","http://www.nuanceinc.com/","desktopトップ: ロゴ画像が上部と本文で重複、料金訴求は画像内、テキスト情報が少ない。問い合わせはナビ内のみ","http://www.nuanceinc.com/","http://www.nuanceinc.com/",vis="verified"),
 rec("2-5ed9bfd13c","active","none","stop","河合塾グループ日米英語学院と日能研関西の提携教室で大手ブランド運営の校舎。個人・小規模Segment対象外","「西宮北口駅第2教室で生徒募集中」「小学生の英検対策コース開講」と掲載","https://miraenglish.com/","desktopトップに「河合塾グループ 日米英語学院 × 日能研関西」ロゴ。本部運営サイト","https://miraenglish.com/","https://miraenglish.com/","河合塾グループ日米英語学院×日能研関西の提携校舎(https://miraenglish.com/ のロゴ表記で確認)。大手ブランド運営でSegment対象外","verified"),
 rec("academy-76568bba9c","uncertain","none","stop","個人教室の公式サイトだが写真・訴求とも完成度が高く、トップから明確な提案余地が見えない。今回は深掘りしない","苦楽園口駅徒歩3分、英検対策・合格実績の訴求。更新日は未確認","https://www.eigoterakoyaacademy.com/","desktopトップ: 教室写真、ロゴ、メニューが整い訴求が明確。デザインは現代的","https://www.eigoterakoyaacademy.com/","https://www.eigoterakoyaacademy.com/",vis="verified"),
 rec("lead-419fec3866","active","none","stop","最近のお知らせ更新あり、サイトは整理・導線とも良好で提案余地が見えない。今回は深掘りしない","お知らせに2026.09.10付の記事、無料体験受付中","https://www.sanaijuku.com/","desktopトップ: ヒーロー、CTA、お知らせ、ナビが整理済み","https://www.sanaijuku.com/","https://www.sanaijuku.com/",vis="verified"),
 rec("lead-d6568ee812","active","none","stop","アクシブアカデミーは教室一覧を持つ多校舎展開の大学受験予備校で個人・小規模Segment対象外","無料カウンセリング予約、電話0798-31-1361、校舎ページ運用","https://axivacademy.com/nishikita","desktopトップ: 「教室一覧」ナビ、ブランド統一の本部サイト内校舎ページ","https://axivacademy.com/nishikita","https://axivacademy.com/nishikita","多校舎展開の大学受験予備校ブランド(https://axivacademy.com/nishikita の教室一覧ナビ・本部サイト構成で確認)。個人・小規模Segment対象外","verified"),
 rec("funship-fe660d978d","active","moderate","advance","個人運営とみられる英語教室。新規募集・体験を掲載し活動の手掛かりあり。ヘッダーのロゴ・文字配置がやや不揃いで、体験導線を含め整理余地の可能性","「新規入会生徒募集中」「体験レッスン実施中」、3回体験3000円、公式LINE/メール受付の記載。更新日は不明","https://www.funshipcommunication.com/","desktopトップ: ヘッダーのロゴ/タイトル/ナビ位置が不揃い、配色が強い。お問合せボタンは2箇所あるが詳細導線は下層未確認","https://www.funshipcommunication.com/","https://www.funshipcommunication.com/",vis="verified"),
 rec("ca-mikoenglishtalk-7e8f370daf","uncertain","unknown","defer","個人教室のGoogleサイトだが保存URLが404でトップ内容を確認できない。次回: サイトのトップURLに到達できるか再確認(事業の存在自体は矛盾ではない)","404画面だがナビ(ホーム・体験授業・レッスン時間・航空業界向けレッスン)が表示され、サイトは存在。営業状況は不明","https://sites.google.com/view/mikoenglishtalk/","取得したURLは「入力したページは存在しません」。正しいトップページを未確認のためgap判断不可","https://sites.google.com/view/mikoenglishtalk/","https://sites.google.com/view/mikoenglishtalk/"),
 rec("lead-05d2cc2fd3","active","moderate","advance","塾長運営の数学専門塾で、2026年の案内・満席告知あり。トップは文字量が多く過密、色使いも強く、情報整理・導線の提案余地の可能性","「【重要】一部の学年の満席のお礼と今後のご案内予定2026」を掲載。塾長運営、個別指導","https://suugakuintegral.main.jp/","desktopトップ: 長い説明文が密集、青・黒・緑・赤の強い配色、ヘッダー画像は寄せ集め感。問い合わせ導線は文中に「お問い合わせください」のみ","https://suugakuintegral.main.jp/","https://suugakuintegral.main.jp/",vis="verified"),
 rec("leglabo-7930afb28a","active","none","stop","多コース・講師募集・LINE導線まで揃った整備済みサイトで、トップから明確な提案余地が見えない。今回は深掘りしない","電話・住所(甲風園1-7-3エスアセットビル4F・5F)、講師募集、月間予定表、LINE問い合わせを掲載","https://www.leglabo.jp/","desktopトップ: コース別ボタン、ナビ、お問い合わせ/LINE導線が整理済み。ナビ項目数は多い","https://www.leglabo.jp/","https://www.leglabo.jp/",vis="verified"),
 rec("lead-ff8dde2221","uncertain","moderate","advance","西宮北口の少人数作文・国語塾で、ブログ・時間割・Instagram連携あり。トップのナビが二段で密集し体験導線が弱く整理余地の可能性","教室ブログ、教室カレンダー、時間割・授業料、Instagramのナビあり。最新投稿日は未確認","https://www.kotonoha-sakubun.com/","desktopトップ: ナビが2段12項目で灰背景に小文字、体験・問い合わせの強調CTAがファーストビューに見えない。ロゴ位置が空白","https://www.kotonoha-sakubun.com/","https://www.kotonoha-sakubun.com/",vis="verified"),
]
save("triage-02-out.jsonl", b02)
